- name: postfix installed
  apt:
    pkg: postfix
    state: installed

- name: postfix configured to listen only on loopback interface
  lineinfile:
    line: "inet_interfaces = loopback-only"
    regexp: "^inet_interfaces ="
  notify: Restart postfix

